version: "3.9"

services:
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./production.Dockerfile
    networks:
      - default

networks:
  default:
    driver: bridge
