version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev